spring:
  application:
    name: BeautyBox
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true